name: Publish pre Release package version

on:
  push:
    branches:
      - next

jobs:
  commit:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, 'Release') }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      # setup git user
      - run: git config user.name "$GITHUB_ACTOR"
      - run: git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      # incremnet package version and create a commit
      - run: npm version prerelease --preid=next -m "Release %s"

      - uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.PUSH_ON_NEXT_BRANCH_TOKEN }}
          branch: next

  publish-npm:
    if: ${{ startsWith(github.event.head_commit.message, 'Release') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm run publish -- --tag next
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  deploy-ftp:
    name: Deploy
    if: ${{ !startsWith(github.event.head_commit.message, 'Release') }}
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build

      - name: 📂 Upload Site
        uses: SamKirkland/FTP-Deploy-Action@4.3.1
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          port: ${{ secrets.FTP_PORT }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          local-dir: build/
          server-dir: /
